import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Login from './auth/login'
import Post from './recipes'

export default function Home({posts}) {
  return (
    <div className='h-screen'>
      <Head>
        <title>Recipe App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Post posts={posts} />
    </div>
  )
}

export const getServerSideProps = async (ctx) => {

  const res = await fetch(`${process.env.STRAPI_BACKEND_HOST}/api/posts?populate=*`);  
  const data = await res.json();

  return {
    props: {
      posts: data.data,
    },
  };
};
